#!/bin/bash

export PATH=$PATH:/root/.pyenv/bin/
sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
xz-utils tk-dev libffi-dev liblzma-dev python-openssl python-pip jq

#curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash

#pyenv update

#echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc
#echo 'eval "$(pyenv init -)"' >> ~/.bashrc
#echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
#source ~/.bashrc
#
#pyenv install 2.7.12
#export PYENV_VERSION=2.7.12
#
pip install paramiko
pip install requests
pip install flask
pip install flask_cors
pip install dse-driver
pip install ConfigParser
