#!/bin/bash

export PYENV_VERSION=2.7.12

export FLASK_APP=restDemo.py

#dependencies
pip install -U pyopenssl
pip install -U flask

#run
nohup flask run --host=0.0.0.0 --port=8080 > /tmp/flask.log &

