#!/bin/bash

set -x

HOST_IP=$(ifconfig | awk '/inet/ { print $2 }' | egrep -v '^fe|^127|^192|^172|::' | head -1)
HOST_IP=${IP#addr:}
export IP=$HOST_IP

if [[ $HOSTNAME == "node"* ]] ; then
    #rightscale
    HOST_IP=$(grep $(hostname)_ext /etc/hosts | awk '{print $1}')
    export IP=$HOST_IP
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
    HOST_IP=$(docker run --net=host debian:jessie ip addr show|grep inet|grep eth0|awk '{print $2}'|awk -F'/' '{print $1}')
    export IP=localhost
fi

cd ui

NODE_VERSION=9.10.1
export NODEJS_HOME=/usr/local/lib/nodejs/node-v"${NODE_VERSION}"/bin
export PATH=$NODEJS_HOME:$PATH

npm install
nohup npm run start &
